title: "Parjanya Vyas"
description: "PhD dissertation and publications"
baseurl: ""
url: "https://parjanya-vyas.github.io"
permalink: pretty
remote_theme: "mmistakes/so-simple-theme@3.2.0"

# Navigation
nav:
  - name: "Home"
    link: "/cv"
  - name: "Dissertation"
    link: "/cv/dissertation/"
  - name: "Publications"
    link: "/cv/publications/"
  - name: "About"
    link: "/cv/about/"
  - name: "Contact"
    link: "/cv/contact/"
